CREATE TABLE [security].[GeneratedObjectScripts]
(
	Id BIGINT IDENTITY NOT NULL,
	BatchId BIGINT NOT NULL,
	SchemaName VARCHAR(100) NOT NULL,
	TableName VARCHAR(100) NOT NULL,
	ScriptType VARCHAR(100) NOT NULL,
	Script NVARCHAR(MAX) NOT NULL
)
WITH 
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX (SchemaName ASC, TableName ASC)
)