CREATE TABLE [security].[CLSConfiguration]
(
	ClsId BIGINT IDENTITY NOT NULL,
	SchemaName VARCHAR(100) NOT NULL,
	TableName VARCHAR(100) NOT NULL,
	ColumnName VARCHAR(100) NOT NULL,
	FilterColumnName VARCHAR(100) NULL,
	FilterType VARCHAR(100) NOT NUll,
	IsEnabled BIT NOT NULL,
	InsertedBy VARCHAR(100) NOT NULL,
	InsertedDate DATETIME NOT NULL,
	UpdatedBy VARCHAR(100) NOT NULL,
	UpdatedDate DATETIME NOT NULL
)
WITH
(
	DISTRIBUTION = REPLICATE,
	CLUSTERED INDEX (SchemaName ASC, TableName ASC, ColumnName ASC, FilterType ASC)
)
GO
