CREATE TABLE [security].[Log]
(
	BatchId BIGINT NOT NULL,
	LogId BIGINT IDENTITY NOT NULL,
	ActivityName VARCHAR(500) NOT NULL,
	Text NVARCHAR(MAX) NULL,
	InsertedDate DATETIME NOT NULL,
	InsertedBy VARCHAR(100) NOT NULL	
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED INDEX (BatchId)
)